print("Seeding the collection 'locations' in the 'foodlist' db");

db.locations.insert([
    {
        address: "6220 Avenue U",
        zipcode: "NY 11234",
        borough: "Brooklyn",
        cuisine: "Cafe",
        grade: "A",
        name: "The Roasted Bean",
        on_wishlist: [],
        location_id: "56018",
    },
    {
        address: "103-05 37 Avenue",
        zipcode: "NY 11368",
        borough: "Queens",
        cuisine: "Japanese",
        grade: "A",
        name: "From Tokyo With Love",
        on_wishlist: [],
        location_id: "62432",
    },
    {
        address: "5408 Avenue N",
        zipcode: "NY 11234",
        borough: "Brooklyn",
        cuisine: "Hamburgers",
        grade: "A",
        name: "Happy Bunny Burgers",
        on_wishlist: [],
        location_id: "12340",
    },
    {
        address: "8825 Astoria Boulevard",
        zipcode: "NY 11369",
        borough: "Queens",
        cuisine: "American",
        grade: "B",
        name: "Fries On The Boulevard",
        on_wishlist: [],
        location_id: "56151",
    },
    {
        address: "1 East 66 Street",
        zipcode: "NY 10065",
        borough: "Manhattan",
        cuisine: "Ice Cream",
        grade: "B",
        name: "Frozen & Sweet",
        on_wishlist: [],
        location_id: "61322",
    },
    {
        address: "1366 E 54th St",
        zipcode: "NY 11234",
        borough: "Bronx",
        cuisine: "Bakery",
        grade: "A",
        name: "Happy Bread",
        on_wishlist: [],
        location_id: "75445",
    },
    {
        address: "531 Myrtle Avenue",
        zipcode: "NY 11205",
        borough: "Brooklyn",
        cuisine: "Hamburgers",
        grade: "C",
        name: "White & Black",
        on_wishlist: [],
        location_id: "62344",
    },
    {
        address: "2351 Ralph Ave",
        zipcode: "NY 11234",
        borough: "Brooklyn",
        cuisine: "Italian",
        grade: "A",
        name: "The Artesan's Oven",
        on_wishlist: [],
        location_id: "56442",
    },

    {
        address: "97-22 63 Road",
        zipcode: "NY 11374",
        borough: "Queens",
        cuisine: "Jewish/Kosher",
        grade: "B",
        name: "The Kosher Place",
        on_wishlist: [],
        location_id: "56068",
    },

    {
        address: "6409 11 Avenue",
        zipcode: "NY 11219",
        borough: "Brooklyn",
        cuisine: "American",
        grade: "B",
        name: "Bellyful Of Fries",
        on_wishlist: [],
        location_id: "56649",
    },
    {
        address: "1839 Nostrand Avenue",
        zipcode: "NY 11226",
        borough: "Brooklyn",
        cuisine: "Ice Cream",
        grade: "B",
        name: "Mario's Ice Cream",
        on_wishlist: [],
        location_id: "56731",
    },
    {
        address: "2300 Southern Boulevard",
        zipcode: "NY 10460",
        borough: "Bronx",
        cuisine: "Vietnamese",
        grade: "B",
        name: "Saigon",
        on_wishlist: [],
        location_id: "57217",
    },
    {
        address: "7715 18 Avenue",
        zipcode: "NY 11214",
        borough: "Brooklyn",
        cuisine: "Vietnamese",
        grade: "B",
        name: "The Hanoi Cafe",
        on_wishlist: [],
        location_id: "57437",
    },
    {
        address: "705 Kings Highway",
        zipcode: "NY 11223",
        borough: "Brooklyn",
        cuisine: "Chinese",
        grade: "B",
        name: "The Hot Pot",
        on_wishlist: [],
        location_id: "60045",
    },
    {
        address: "1269 Sutter Avenue",
        zipcode: "NY 11208",
        borough: "Brooklyn",
        cuisine: "Chinese",
        grade: "B",
        name: "Noodle Kitchen",
        on_wishlist: [],
        location_id: "58429",
    },
    {
        address: "265-15 Hillside Avenue",
        zipcode: "NY 11004",
        borough: "Queens",
        cuisine: "American",
        grade: "B",
        name: "Street Kitchen",
        on_wishlist: [],
        location_id: "59480",
    },

    {
        address: "351 West 57 Street",
        zipcode: "NY 10019",
        borough: "Manhattan",
        cuisine: "Irish",
        grade: "B",
        name: "Sean's Bar",
        on_wishlist: [],
        location_id: "91841",
    },
    {
        address: "203 Church Avenue",
        zipcode: "NY 11218",
        borough: "Brooklyn",
        cuisine: "Ice Cream",
        grade: "B",
        name: "Icing",
        on_wishlist: [],
        location_id: "60076",
    },
    {
        address: "6909 3 Avenue",
        zipcode: "NY 11209",
        borough: "Brooklyn",
        cuisine: "Swedish",
        grade: "B",
        name: "Nordic's",
        on_wishlist: [],
        location_id: "61390",
    },
    {
        address: "284 Prospect Park West",
        zipcode: "NY 11215",
        borough: "Brooklyn",
        cuisine: "American",
        grade: "C",
        name: "John's Kitchen",
        on_wishlist: [],
        location_id: "61606",
    },
    {
        address: "759 Broadway",
        zipcode: "NY 10003",
        borough: "Manhattan",
        cuisine: "Delicatessen",
        grade: "C",
        name: "The Deli At The Corner",
        on_wishlist: [],
        location_id: "61708",
    },
    {
        address: "129-08 20 Avenue",
        zipcode: "NY 11356",
        borough: "Queens",
        cuisine: "Delicatessen",
        grade: "C",
        name: "Queens Deli",
        on_wishlist: [],
        location_id: "61618",
    },
    {
        address: "3406 10 Street",
        zipcode: "NY 11106",
        borough: "Queens",
        cuisine: "Delicatessen",
        grade: "C",
        name: "Bagels Plus",
        on_wishlist: [],
        location_id: "61998",
    },
    {
        address: "522 East   74 Street",
        zipcode: "NY 10021",
        borough: "Manhattan",
        cuisine: "American",
        grade: "C",
        name: "Greasy Food",
        on_wishlist: [],
        location_id: "61521",
    },
    {
        address: "730 Columbus Avenue",
        zipcode: "NY 10025",
        borough: "Manhattan",
        cuisine: "American",
        grade: "C",
        name: "The Corner Grocery",
        on_wishlist: [],
        location_id: "62264",
    },
    {
        address: "502 Amsterdam Avenue",
        zipcode: "NY 10024",
        borough: "Manhattan",
        cuisine: "Chicken",
        grade: "C",
        name: "Janet's Kitchen",
        on_wishlist: [],
        location_id: "62098",
    },
    {
        address: "18 West Houston Street",
        zipcode: "NY 10012",
        borough: "Manhattan",
        cuisine: "American",
        grade: "C",
        name: "Movie Central",
        on_wishlist: [],
        location_id: "62274",
    },

    {
        address: "60 Wall Street",
        zipcode: "NY 10005",
        borough: "Manhattan",
        cuisine: "Turkish",
        grade: "C",
        name: "The Doener",
        on_wishlist: [],
        location_id: "62715",
    },
    {
        address: "195 East   56 Street",
        zipcode: "NY 11203",
        borough: "Brooklyn",
        cuisine: "Caribbean",
        grade: "C",
        name: "Crabs At The Curb",
        on_wishlist: [],
        location_id: "62869",
    },

    {
        address: "7020 Avenue U",
        zipcode: "NY 11234",
        borough: "Brooklyn",
        cuisine: "Jewish/Kosher",
        grade: "A",
        name: "Gourmet Bagels",
        on_wishlist: [],
        location_id: "56483",
    },
    {
        address: "56 Court Street",
        zipcode: "NY 11201",
        borough: "Brooklyn",
        cuisine: "Donuts",
        grade: "A",
        name: "Sally's Donuts",
        on_wishlist: [],
        location_id: "63098",
    },
    {
        address: "7615 5 Avenue",
        zipcode: "NY 11209",
        borough: "Brooklyn",
        cuisine: "Greek",
        grade: "A",
        name: "The Break",
        on_wishlist: [],
        location_id: "63117",
    },
    {
        address: "1006 East 233 Street",
        zipcode: "NY 10466",
        borough: "Bronx",
        cuisine: "Ice Cream",
        grade: "A",
        name: "Iceland",
        on_wishlist: [],
        location_id: "63093",
    },
    {
        address: "1236 238 Spofford Ave",
        zipcode: "NY 10474",
        borough: "Bronx",
        cuisine: "Thai",
        grade: "A",
        name: "Same Same",
        on_wishlist: [],
        location_id: "63289",
    },
    {
        address: "120 Prince Street",
        zipcode: "NY 10012",
        borough: "Manhattan",
        cuisine: "Greek",
        grade: "A",
        name: "Kostas'",
        on_wishlist: [],
        location_id: "63151",
    },
    {
        address: "107 Church Street",
        zipcode: "NY 10007",
        borough: "Manhattan",
        cuisine: "American",
        grade: "A",
        name: "Downtown Bagels",
        on_wishlist: [],
        location_id: "63021",
    },
    {
        address: "1069 Wyckoff Avenue",
        zipcode: "NY 11385",
        borough: "Queens",
        cuisine: "Ice Cream",
        grade: "A",
        name: "Spitzbergen",
        on_wishlist: [],
        location_id: "63333",
    },
    {
        address: "625 8 Avenue",
        zipcode: "NY 10018",
        borough: "Manhattan",
        cuisine: "American",
        grade: "A",
        name: "The Coffee Grinder",
        on_wishlist: [],
        location_id: "63298",
    },
    {
        address: "2491 Victory Boulevard",
        zipcode: "NY 10314",
        borough: "Staten Island",
        cuisine: "Delicatessen",
        grade: "A",
        name: "Little Europe",
        on_wishlist: [],
        location_id: "63427",
    },
    {
        address: "405 Lexington Avenue",
        zipcode: "NY 10174",
        borough: "Manhattan",
        cuisine: "American",
        grade: "A",
        name: "The Diner At The Corner",
        on_wishlist: [],
        location_id: "63426",
    },
]);

print("Completed seeding MongoDB!");
